package org.gym.dao;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import org.gym.object.Program;

import java.util.List;

/**
 * Created by AndreyNick on 12.11.2014.
 */
public class ProgramAdapter {

    public static String TABLE_NAME = "program";
    public static String ID = "_id";
    public static String NAME = "name";
    public static String DESCRIPTION = "description";
    private SQLiteDatabase db;

    protected ProgramAdapter(SQLiteDatabase db){
        this.db = db;
    }


    public List<Program> getAllPrograms(){
        return null;
    }

    public void setPrograms(List<Program> programList){
        for(Program program : programList){
            setProgram(program);
        }
    }

    public void setProgram(Program program){

        ContentValues values = new ContentValues();
        values.put(NAME, program.getName());
        values.put(DESCRIPTION, program.getDescription());

        db.insert(TABLE_NAME, null, values);  //it can return autogenerated ID
    }
}
